### ISSUE TITLE
About page "Manually building a tile server (18.04 LTS)"

### ISSUE THREAD

**Issue by Silka123** [switch2osm/switch2osm.github.io#102]
Page "Manually building a tile server (18.04 LTS)" (https://switch2osm.org/serving-tiles/manually-building-a-tile-server-18-04-lts/). 

First it is written that " renderd provides a priority queueing system for rendering requests to manage and smooth out the load from rendering requests. Mapnik is the software library that does the actual rendering and is used by renderd."

But then in the section "Install mod_tile and renderd" the following is reported:

"“renderd” is a daemon that actually renders the tiles when “mod_tile” requests them. "

Is there no contradiction in this?

**Comment by SomeoneElseOSM** [comment]
What it says is actually correct.  What doesn't say explicitly is that there are several ways that tiles can get rerendered:

* when a user has asked for a particular tile, and there is no tile for that location.
* when a user has asked for a tile, and there is an up-to-date tile already there
* when a user has asked for a tile, and there is an old tile available, but a new one needs to be created
* when the system explicitly runs a background rendering request (often done for low-zoom tiles at less busy times of day)
* optionally, if configured to do so, new tiles can be rerendered whenever an old tile is marked "dirty"

It'd be way too complicated to put all this in one guide, since you don't need to understand any of it just to get a tile server working.  Maybe there's scope for a separate document called "you've just installed a rendering server - how does it work?"  There are a few other things I'd want to add first though to other pages.  I've changed the text slightly (see https://github.com/switch2osm/switch2osm.github.io/pull/103 ) to hopefully make things a bit clearer, so I'll close this.
