### ISSUE TITLE
"Building a tile server from packages" update or removal

### ISSUE THREAD

**Issue by nmxcgeo** [switch2osm/switch2osm.github.io#120]
Hello,

I suggest the page [Building a tile server from packages](https://switch2osm.org/serving-tiles/building-a-tile-server-from-packages/) to be updated or removed. 

In this tutorial you are suggesting Ubuntu 12.04 LTS and 14.04 LTS which are both [out of support](https://wiki.ubuntu.com/TrustyTahr/ReleaseNotes).

Furthermore there exists at least one [tutorial for Ubuntu 18.04 LTS](https://www.linuxbabe.com/ubuntu/openstreetmap-tile-server-ubuntu-18-04-osm), that uses packages rather than building from source. I don't know whether it works and if it's a good/recommended way to set up a tile server, but at least it seems to be possible.

If an update [as also suggested in Issue #26](https://github.com/switch2osm/switch2osm.github.io/issues/26#issuecomment-248840972) is too complex I'd say that it is better to remove these outdated instructions rather than recommend unsupported operating systems.

Greetings
Nmxcgeo

**Comment by SomeoneElseOSM** [comment]
> I suggest the page "Building a tile server from packages" to be updated or removed.

I was going to remove it last year but tested it and found that it still worked, so left it in.  I moved it to the end of the list, as Ubuntu 14.04 was (at the time) still supported.  At some stage we'll just remove it.  If you want to submit a pull request to do that, I'll happily accept it.

> Furthermore there exists at least one tutorial for Ubuntu 18.04 LTS, that uses packages rather than building from source.

It's good that there are lots of different tutorials around that approach the problem from a different angle.  That one includes consideration about importing the whole planet (which I wouldn't recommend for a first-timer, but which will be useful for some people).

> I don't know whether it works and if it's a good/recommended way to set up a tile server, but at least it seems to be possible.

I don't think that we should link to anything that we haven't tested.  I have updated both https://switch2osm.org/serving-tiles/manually-building-a-tile-server-18-04-lts/ and https://switch2osm.org/serving-tiles/using-a-docker-container/ recently as some of the prereqs (expletive expletive node.js expletive expletive) changed.

The manual building of osm2pgsql in the 18.04 guide is because historically it needed to be done manually otherwise it wouldn't work, though that is going back at least one release.  I'm aware that osm2pgsql developers are still keen that users are on later released versions (just have a look at the github issues for it) so I'd be tempted to leave that in.

I'd suggest that https://switch2osm.org/serving-tiles/using-a-docker-container/ is a good first step for people who want to do the minimum work just to try something (people who might have used "for packages" before).

Looking not that far into the future we'll need guides for Ubuntu 20.04 at [the end of this month](https://www.omgubuntu.co.uk/2019/10/ubuntu-20-04-release-features).

**Comment by pnorman** [comment]
> The manual building of osm2pgsql in the 18.04 guide is because historically it needed to be done manually otherwise it wouldn't work, though that is going back at least one release

Manually building osm2pgsql hasn't been necessary since 14.04 or 16.04.
