### ISSUE TITLE
Improvements for 20.04 tile server tutorial

### ISSUE THREAD

**Issue by esgn** [switch2osm/switch2osm.github.io#132]
Hi,

A few things that could be improved in the tutorial regarding the Ubuntu 20.04 tile server

* renderaccount user creation
  * Either use `adduser` and `usermod` or pass the necessary options to `useradd` to get bash instead of sh shell and put renderaccount in sudo group
  * Tell the user to use the renderaccount for the rest of the tutorial (add a su command to the tutorial ?). I've seen many users doing all the work with their current user account to finally detect that something was not ok at the osm2pgsql step

* Many users completely miss the RUNASUSER check and just open and close with `nano ~/src/mod_tile/debian/renderd.init`

* Would it be possible to add something regarding database update (with osmosis and osm2pgsql typically) ?
 
Anyway thanks for all the work, 

Cheers

**Comment by SomeoneElseOSM** [comment]
Addressing these in reverse order:

- https://switch2osm.org/serving-tiles/updating-as-people-edit/ (got there eventually)

- I'm not sure I can make 'edit the “~/src/mod_tile/debian/renderd.init” file so that “RUNASUSER” is set to the non-root account that you have used before,' any clearer.  Any suggestions?

- (re bash instead of sh shell) yes, that would make sense

- (re use the renderaccount for the rest of the tutorial) I think tried to reword this a bit (certainly the Debian one is clearer).  Any suggestions for text that ought to be in there?

**Comment by SomeoneElseOSM** [comment]
I've addressed most of these now, I think.  No further comments, so I'll close the issue.
