### ISSUE TITLE
Manually building a tile server (20.04 LTS) with Postgres 13

### ISSUE THREAD

**Issue by fi4sk0** [switch2osm/switch2osm.github.io#155]
Hi there, 

I just followed https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/ with a fresh ubuntu install and it failed at the `CREATE EXTENSION postgis;` because it doesn't find `postgis.control`. My guess is that this is due to PostgreSQL 13 is installed when executing `sudo apt install postgresql`while the other packages assume version 12 to be installed. 

I solved this by uninstalling everything PostgreSQL related (`sudo apt remove postgresql*`) and using the same commands as in the tutorial but adding `-12` where applicable.

Apart from this small hiccup, thanks for the great work!

**Comment by SK53** [comment]
When I look at switch2osm for Ubuntu 20.04 LTS it looks to me that the commands for PostgreSQL installation specifically ask for version 12 and PostGIS 3.

`sudo apt install postgresql postgresql-contrib postgis postgresql-**12**-postgis-3 postgresql-**12**-postgis-3-scripts`

It would be fairly remarkable to expect that a different version of the database software would work as is: changing database software versions usually involves quite a bit of testing & OSM makes use of PostgreSQL all over the place.

If you just used a basic install command instead of the one above then I think this issue can be closed.

**Comment by fi4sk0** [comment]
My apologies. I'm in the process of trying again and I must have messed something up the last time, because this time it seems to be working.
