### ISSUE TITLE
Problems with Manually building a tile server (Ubuntu 16.04.2 LTS)

### ISSUE THREAD

**Issue by bpg-software** [switch2osm/switch2osm.github.io#177]
Hi,
I am trying to build an OSM Server with a Linux box and Ubuntu 16.04 following the guide [Manually building a tile server (Ubuntu 16.04.2 LTS)](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-16-04-2-lts/).
I am not an expert and I found some problems:

1) `createdb -E UTF8 -O renderaccount gis`
I receive:
	_createdb: database creation failed: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)
	HINT:  Use the same encoding as in the template database, or use template0 as template._
and I solve it using:
```
psql
	UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';
	DROP DATABASE template1;
	CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';
	UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';
	\c template1
	VACUUM FREEZE;
\q

```

2) `carto -v`
I receive:
	_/usr/local/lib/node_modules/carto/node_modules/yargs/lib/command.js:22
	    globalMiddleware.push(...middlewares)
	                          ^^^
	
	SyntaxError: Unexpected token ...
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:374:25)
	    at Object.Module._extensions..js (module.js:417:10)
	    at Module.load (module.js:344:32)
	    at Function.Module._load (module.js:301:12)
	    at Module.require (module.js:354:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/usr/local/lib/node_modules/carto/node_modules/yargs/lib/argsert.js:2:17)
	    at Module._compile (module.js:410:26)
	    at Object.Module._extensions..js (module.js:417:10)_
and I solve updating node to last stable version

3) `scripts/get-external-data.py`
I receive:
	_Traceback (most recent call last):
	  File "scripts/get-external-data.py", line 29, in <module>
	    import psycopg2
	ImportError: No module named 'psycopg2'_

and I don't know how to solve it because if I run "pip2 list" I receive:
psycopg2 2.6.1
psycopg2-binary 2.8.6

and with "python --version" I receive
Python 2.7.12

I already tried to install python-psycopg2 with apt-get and psycopg2-binary using pip or pip2 but I have the same error.

Someone have some suggestions?

Thanks a lot

**Comment by SomeoneElseOSM** [comment]
I haven't tried using the Ubuntu 16.04 instructions for a while - as per https://ubuntu.com/about/release-cycle , regular support ended last year.  The message "is incompatible with the encoding of the template database" is odd, because those instructions work used to just fine on  a new server, and I can't believe that Ubuntu has changed since it is no longer in regular support.

What system are you actually using?  Is it perhaps not a vanilla Ubuntu 16.04 system but actually one that had lots of things done to it since it was installed (possibly several years ago).  Can you describe in more detail what system you are actually trying to run this on?  Is there any reason why you are restricted to Ubuntu 16.04 and not something more recent?

**Comment by bpg-software** [comment]
I am using Ubuntu 16.04 because I try to build an OSM server with a PC Engines APU2 board, and this is an OS suggested in PC Engines web site.
Today I discovered that python3 is needed by get-external-data.py so using 
`update-alternatives --install /usr/bin/python python /usr/bin/python3 1`
I switch from python2 to python3 and, after installation of python3-psycopg2 (via apt),  get-external-data.py is successfully completed.
Now I am trying to import a pbf in the database, it's a long operation, I will let you know if all works fine.

Thank you very much

**Comment by SomeoneElseOSM** [comment]
> I am using Ubuntu 16.04 because I try to build an OSM server with a PC Engines APU2 board, and this is an OS suggested in PC Engines web site.

I'm not familiar with this hardware, but I'd suggest trying to find out if they're suggesting that because later versions of Ubuntu or Debian explicitly aren't supported, or because they just haven't updated their website in a few years?

If the latter, then either a later Ubuntu LTS version or Debian 11 might be a better bet - Debian 11 offers both the latest osm2pgsql et al and, if I read https://wiki.debian.org/LTS correctly, support until 2026.

**Comment by bpg-software** [comment]
Thank you @SomeoneElseOSM for your suggestions, maybe I will check for OS supported by APU2.
Now, after 1 hour of import, the command faill with:
```
ERROR: DB copy thread failed: Ending COPY mode for 'planet_osm_nodes' failed: ERROR:  could not extend file "base/16386/23403.2": wrote only 4096 of 8192 bytes at block 357790
HINT:  Check free disk space.
CONTEXT:  COPY planet_osm_nodes, line 66192000
```
In my board I have a 16GB SSD, now is full, I am trying to import italy-latest.osm.pbf.
Do you have an estimate of how much space I need for this pbf (of 168 MB)?

Thank you

**Comment by SomeoneElseOSM** [comment]
> In my board I have a 16GB SSD, now is full, I am trying to import italy-latest.osm.pbf.
> Do you have an estimate of how much space I need for this pbf (of 168 MB)?

I think you mean 1.6GB: https://download.geofabrik.de/europe/italy.html

I can't comment on Italy, but a tile server I look after with a slightly different style currently has a database size (of everything inside /var/lib/postgresql ) of 64GB based on Britain and Ireland, also a 1.6GB download: https://download.geofabrik.de/europe/britain-and-ireland.html .

I'd suggest trying a _much_ smaller file first, maybe Liechtenstein?

**Comment by bpg-software** [comment]
> I think you mean 1.6GB: https://download.geofabrik.de/europe/italy.html
Yes, sorry, 1,6 GB

Now, I changed my SDD from 16GB to 120GB and I restarted the import process.
After about 8 hours it finished with success, DB folder is about 50GB.

All seems work fine, my only problem, but maybe due to board CPU, is that for a single tile I need to wait from 80 to 300 seconds (I see these times running in foreground or in syslog for service). Is there a way to increase speed?

Moreover I see that server has a permanent cache because if I request the same tile (also after reboot) the response is immediately. Do you know where is the cache, if is there a config file and  if is there a way to clear it?

Thank you very much for your support

**Comment by SomeoneElseOSM** [comment]
> All seems work fine, my only problem, but maybe due to board CPU, is that for a single tile I need to wait from 80 to 300 seconds (I see these times running in foreground or in syslog for service). Is there a way to increase speed?

Get a faster computer?

More seriously, it's actually pretty normal to wait a while the first time that a complicated tile is rendered.  The idea is that the next time that someone renders a tile, it'll be there for them - not necessarily completely up to date, but they will see some data.  

It's also a good idea to "pre-render" low-zoom tiles (perhaps up to zoom 12) so that these tiles are ready for your first website visitor.  "render_list" can be used for that, but if you just want to render tiles for a particular area you can use something like "render_list_geo" - see https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load#Force_Rendering_Tiles for information.

I'll close this issue, as I don't believe that there is a problem with the 16.04 guide.  It already has a big caveat "... but if you absolutely still need a server based upon 16.04 ..." in it, which is designed to nudge people toward more recent versions.

**Comment by bpg-software** [comment]
I will see in the future if i can change the board, now my primary goal was to use APU2 as server.
I think a pre-render will be a good compromise, maybe increasing cache duration.
Thank you very much @SomeoneElseOSM for your great help.
