### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [switch2osm/switch2osm.github.io#40]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Switch2osm [seems to be recommending osmosis](https://github.com/switch2osm/switch2osm.github.io/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis), which [will not follow redirects by default](https://trac.openstreetmap.org/ticket/5483).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https? All services respond over https and will start redirecting soon.

**Comment by SomeoneElseOSM** [comment]
https://github.com/switch2osm/switch2osm.github.io/blob/master/serving-tiles/manually-building-a-tile-server-16-04-2-lts.md is just a copy of the Wordpress site as of a week or so ago.  That documentation has been changed so that it works now that planet.osm.org redirects to https.

https://github.com/switch2osm/switch2osm.github.io/blob/89cdacbebe9b196915920e7e7d52a0cffc1a5501/serving-tiles/building-a-tile-server-from-packages.md is pretty archaic and arguably shouldn't really be there any more at all.

There are bigger issues here than which protocol a particular obsolete page uses.  If you'd like to help, perhaps you could have a look at the problems causing https://github.com/switch2osm/switch2osm.github.io/pull/39#issuecomment-374567893 ?
